<?php

namespace MikeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Products_sizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Products_sizesRepository extends EntityRepository
{
}
