<?php

namespace MikeBundle\Repository;

/**
 * SizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizesRepository extends \Doctrine\ORM\EntityRepository
{
}
